kind:
  allowed:
    - operator
  required: true
  type: string
  default: operator
  meta:
    description: "Which service are you trying to use? Common kinds: `operator`, `job`"

version:
  allowed:
    - "v1"
  required: true
  type: string
  default: v1
  meta:
    description: "Operators may change yaml file schemas from version to version, as well as implementation details. Double check the version to ensure compatibility."

type:
  required: true
  type: string
  default: feature_store_marketplace
  meta:
    description: "Type should always be `feature_store_marketplace` when using a feature_store_marketplace operator"

spec:
  required: true
  schema:
    helm:
      required: true
      type: dict
      meta:
        description: "Helm related details"
      schema:
        appName:
          required: true
          type: string
          meta:
            description: "Helm app name"
          default: "feature-store-api"
        values:
          required: true
          type: dict
          meta:
            description: "Values being provided to helm chart"
          schema:
            mysqlDBConfig:
              type: dict
              required: false
              meta:
                description: "Configuration details on how to connect to MySQL DB"
              schema:
                user:
                  type: string
                  required: true
                  default: "admin"
                url:
                  type: string
                  required: true
                  default: "<Enter jdbc url to connect to mysql here>"
                password:
                  type: string
                  required: true
                  default: "<Enter password to mysql user here>"
            atpDBConfig:
              type: dict
              required: false
              schema:
                vaultOCID:
                  type: string
                  required: true
                dbURL:
                  type: string
                  required: true
            configuredDB:
              type: string
              required: true
              default: MYSQL
              allowed:
                - MYSQL
                - ATP
    clusterDetails:
      required: true
      type: dict
      schema:
        namespace:
          type: string
          required: true
          default: "default"
          description: "Namespace where we want to deploy the cluster to. Eg: 'default'"
        dockerRegistrySecretName:
          type: string
          required: false
          default: "ocir-secret"
          description: "Operator will create a secret using user's bearer token if this registry isn't manually provided"
    ocirRepo:
      type: string
      required: true
      default: "iad.ocir.io/<repository>"
      description: "The ocir repo to clone the marketplace listing to"
    compartmentId:
      type: string
      required: true
      default: "<Enter compartment id for deployment here>"
      description: "Compartment id to use for marketplace export"

  type: dict
