name: PII
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - datapane
      - scrubadub
      - "git+https://github.com/oracle/accelerated-data-science.git@feature/ads_pii_operator#egg=oracle-ads"
