name: pii
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - aiohttp
      - datapane
      - gender_guesser
      - nameparser
      - plotly
      - scrubadub
      - scrubadub_spacy
      - "git+https://github.com/oracle/accelerated-data-science.git@feature/ads_pii_operator#egg=oracle-ads"
