kind:
  allowed:
    - operator
  required: true
  type: string
  default: operator
  meta:
    description: "Which service are you trying to use? Common kinds: `operator`, `job`"

version:
  allowed:
    - "v1"
  required: true
  type: string
  default: v1
  meta:
    description: "Operators may change yaml file schemas from version to version, as well as implementation details. Double check the version to ensure compatibility."

type:
  required: true
  type: string
  default: pii
  meta:
    description: "Type should always be `pii` when using a pii operator"


spec:
  required: true
  schema:
    input_data:
      required: true
      type: dict
      meta:
        description: "This should be indexed by target column."
      schema:
        format:
          allowed:
            - csv
            - json
          required: false
          type: string
        columns:
          required: false
          type: list
          schema:
            type: string
        options:
          nullable: true
          required: false
          type: dict
        url:
          required: true
          type: string
          default: data.csv
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/data.csv`"
        limit:
          required: false
          type: integer

    output_directory:
      required: false
      schema:
        format:
          required: false
          type: string
          allowed:
            - csv
            - json
        url:
          required: true
          type: string
          default: result/
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/`"
        name:
          required: false
          type: string
        options:
          nullable: true
          required: false
          type: dict
      type: dict

    report:
      required: false
      schema:
        report_filename:
          required: false
          type: string
          default: report.html
          meta:
            description: "Placed into output_directory location. Defaults to report.html"
        show_rows:
          required: false
          type: integer
          default: 25
        show_sensitive_content:
          required: false
          default: false
          type: bool
      type: dict

    target_column:
      type: string
      required: true
      default: target

    redactor:
      type: dict
      required: true
      schema:
        detectors:
          required: false
          type: list
          schema:
            type: string
          meta:
            description: "default detectors supported by scrubadub"

        spacy_detectors:
          type: dict
          required: false
          schema:
            model:
              type: string
              required: true
              default: en_core_web_trf
            named_entities:
              type: list
              required: true
              default: ["PERSON"]
              schema:
                type: string
          meta:
            description: "Apply spacy model to detect the target entities."

        anonymization:
          type: list
          required: false
          schema:
            type: string
          meta:
            description: "Anonylze the selected entities."
  type: dict
