kind:
  allowed:
    - operator
  required: true
  type: string
  default: operator

version:
  allowed:
    - "v1"
  required: true
  type: string
  default: v1
  meta:
    description: "Operators may change yaml file schemas from version to version, as well as implementation details. Double check the version to ensure compatibility."

type:
  required: true
  type: string
  default: pii
  meta:
    description: "Type should always be `pii` when using a PII operator"

spec:
  required: true
  schema:
    name:
      required: false
      type: string
      default: PII
    report_file_name:
      required: false
      type: string
      default: report.html
      meta:
        description: "Placed into output_directory location. Defaults to report.html"
    report_title:
      required: false
      type: string
      default: PII Report
    report_theme:
      required: false
      type: string
      default: light
      allowed:
        - light
        - dark
    input_data:
      required: true
      type: dict
      meta:
        description: "The input data for the PII."
      schema:
        format:
          allowed:
            - csv
            - json
            - clipboard
            - excel
            - hdf
            - feather
            - load_files
          required: false
          type: string
        columns:
          required: false
          type: list
          schema:
            type: string
        options:
          nullable: true
          required: false
          type: dict
        url:
          required: true
          type: string
          default: data.csv
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/data.csv`"
        limit:
          required: false
          type: integer
    output_directory:
      required: false
      schema:
        connect_args:
          nullable: true
          required: false
          type: dict
        format:
          required: false
          type: string
          allowed:
            - csv
            - json
            - clipboard
            - excel
            - hdf
            - sql
        url:
          required: true
          type: string
          default: result/
          meta:
            description: "The url can be local, or remote. For example: `oci://<bucket>@<namespace>/`"
        name:
          required: false
          type: string
        options:
          nullable: true
          required: false
          type: dict
      type: dict
  type: dict
