name: forecast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - prophet
      - neuralprophet
      - pmdarima
      - statsmodels
      - datapane
      - cerberus
      - json2table
      - sktime
      - optuna==2.9.0
      - ./oracle_ads-2.8.7b0-py3-none-any.whl
      - ./automlx-23.2.1-py38-none-any.whl
