name: forecast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - prophet
      - neuralprophet
      - pmdarima
      - statsmodels
      - datapane
      - cerberus
      - json2table
      - ./oracle_ads-2.8.7b0-py3-none-any.whl
