name: Forecast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - oracle-ads>=2.9.0
      - prophet
      - neuralprophet
      - pmdarima
      - statsmodels
      - report-creator
      - cerberus
      - sktime
      - shap
      - autots[additional]
      - optuna
      - fire
