# This composite action is to avoid duplicating code across test actions.
# Ref: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: "Test env setup"
description: "Creates conda test env with optional dependencies to run all unit tests"
runs:
  using: composite
  steps:
    - shell: bash
      env:
        # torch > v2.1.0 brings nvidia dependency by default, we want to install torch for cpu for tests.
        # Fot that --index-url https://download.pytorch.org/whl/cpu needed - https://pytorch.org/get-started/locally/.
        # Setting env variable here instead of flag --index-url (docs: https://pip.pypa.io/en/stable/cli/pip_install/):
        PIP_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
      run: |
        set -x # print commands that are executed

        sudo apt update
        sudo apt-get install libkrb5-dev graphviz
        $CONDA/bin/conda init
        source /home/runner/.bashrc
        conda install python=${{ matrix.python-version }}
        pip install -r dev-requirements.txt
        conda list
