name: Forecast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - oci-cli
      - "git+https://github.com/oracle/accelerated-data-science.git@feature/feature_store_operator#egg=oracle-ads"
