kind:
  allowed:
    - operator
  required: true
  type: string
  default: operator
  meta:
    description: "The type of the workload."

version:
  allowed:
    - "v1"
  required: true
  type: string
  default: v1
  meta:
    description: "Operators may change yaml file schemas from version to version, as well as implementation details. Double check the version to ensure compatibility."

type:
  required: true
  type: string
  default: feature_store
  meta:
    description: "The type of the operator."

spec:
  required: true
  type: dict
  schema:
    operation:
      required: true
      type: string
      allowed:
        - create
        - update
      default: create
      meta:
        description: "The type of the operation."

    stack_id:
      required: true
      type: string
      meta:
        description: "The Resource Manager stack OCID."

    service_version:
      required: false
      type: string
      meta:
        description: "The service version."

    tenancy_id:
      required: false
      type: string
      meta:
        description: "The tenancy OCID."

    compartment_id:
      required: false
      type: string
      meta:
        description: "The compartment OCID."

    region:
      required: false
      type: string
      meta:
        description: "The region."

    user_id:
      required: false
      type: string
      meta:
        description: "The user OCID."
