name: "Publish Docs"

on:
  # Auto-trigger this workflow on tag creation
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-n-publish:
    name: Build and publish Docs 📖 to Readthedocs
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Readthedocs build
        env:
          RTDS_ADS_PROJECT: https://readthedocs.org/api/v3/projects/accelerated-data-science
          RTDS_ADS_TOKEN: ${{ secrets.RTDS_ADS_TOKEN }}
        run: |
          curl \
            -X POST \
            -H "Authorization: Token $RTDS_ADS_TOKEN" $RTDS_ADS_PROJECT/versions/${{ github.ref_name }}/builds/
