name: tests/unitary/**

on:
  workflow_dispatch:

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

# hack for https://github.com/actions/cache/issues/810#issuecomment-1222550359
env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

jobs:
  test:
    # name: python ${{ matrix.python-version }}, ${{ matrix.name }}
    name: python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8", "3.9"]
        # test-path: ["tests/unitary", "tests/unitary/with_extras/model"]
        test-path: ["tests/unitary/default_setup"]
        # include:
        #   - test-path: "tests/unitary"
        #     ignore-path: "tests/unitary/with_extras/model"
        #     name: "unitary tests"
        #   - test-path: "tests/unitary/with_extras/model"
        #     name: "model tests"

    steps:
      - uses: actions/checkout@v3

      # Caching python libraries installed with pip
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Test config setup"
        shell: bash
        env:
          HOME_RUNNER_DIR: /home/runner
        run: |
          set -x # print commands that are executed
          mkdir -p "$HOME_RUNNER_DIR"/.oci
          openssl genrsa -out $HOME_RUNNER_DIR/.oci/oci_ads_user.pem 2048
          cat <<EOT >> "$HOME_RUNNER_DIR/.oci/config"
          [DEFAULT]
          user=ocid1.user.oc1..xxx
          fingerprint=00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
          tenancy=ocid1.tenancy.oc1..xxx
          region=test_region
          key_file=$HOME_RUNNER_DIR/.oci/oci_ads_user.pem
          EOT
          ls -lha "$HOME_RUNNER_DIR"/.oci
          echo "Test config file:"
          cat $HOME_RUNNER_DIR/.oci/config

      - name: "Test env setup"
        timeout-minutes: 20
        shell: bash
        run: |
          set -x # print commands that are executed
          # sudo apt-get install libkrb5-dev graphviz
          $CONDA/bin/conda init
          source /home/runner/.bashrc
          pip install -r test-requirements.txt

      - name: "Run unitary tests folder with maximum ADS dependencies"
        timeout-minutes: 60
        shell: bash
        env:
          NB_SESSION_COMPARTMENT_OCID: ocid1.compartment.oc1.<unique_ocid>
          CONDA_PREFIX: /usr/share/miniconda
          NoDependency: True
        run: |
          export COVERAGE_FILE="test_cov" && \
          python -m pytest -v -p no:warnings --durations=5 \
          -n auto --dist loadfile \
          --cov=ads --cov-report= \
          ${{ matrix.test-path }} \
          --ignore "${{ matrix.ignore-path }}"
          ls -lha

#       Uploading test artifacts
#       https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts
      - name: "Save coverage files"
        uses: actions/upload-artifact@v3
        with:
          # name: code-coverage-${{ matrix.name }}
          name: code-coverage-${{ matrix.python-version }}
          path: |
            *test_cov.*
            !test_cov

  coverage-report:
    name: "Save html coverage report"
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v3
      - name: "Download coverage files"
        uses: actions/download-artifact@v3
      - name: "Display structure of downloaded files"
        run: ls -R
      - name: "Combine coverage files and generate html report"
        run: |
          pip install coverage
          export COVERAGE_FILE="test_cov" && \
          coverage combine code-coverage-3.8/ code-coverage-3.9/ && \
          coverage html
      - name: "Save coverage report"
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-html-report
          path: htmlcov/
          retention-days: 10
